version: 2

defaults: &defaults
  working_directory: ~/code

  docker:
    - image: circleci/android:api-30-node

  environment:
    JVM_OPTS: -Xmx3200m
    GRADLE_OPTS: -Dorg.gradle.daemon=true -Dorg.gradle.parallel=true

cache_key: &cache_key
  key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

jobs:

  debug-build:
    <<: *defaults

    steps:
      - checkout

      - restore_cache:
          <<: *cache_key

      - run:
          name: Give exec permissions
          command: sudo chmod +x ./gradlew

      - run:
          name: Download dependencies
          command: ./gradlew androidDependencies

      - run:
          name: Run unit tests
          command: ./gradlew testDebugUnitTestCoverage

      - run:
          name: Upload code coverage report
          command: bash <(curl -s https://codecov.io/bash) -f "*.xml"

      - run:
          name: Run detekt
          command: ./gradlew detekt

      - run:
          name: Run Android lint
          command: ./gradlew lintDebug

      - store_artifacts:
          path: reports/
          destination: reports

      - store_test_results:
          path: app/test/test-results

      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle.kts" }}-{{ checksum "app/build.gradle.kts" }}

workflows:
  version: 2

  main:
    jobs:
      - debug-build
